# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Proyectos',  url: 'proyectos'}
- {name: 'Biblioteca', url: 'biblioteca'}
- {name: 'Portafolio',       url: 'sample-posts'}
- {name: 'Documentos',      url: 'documentation'}
- {name: 'Pedro López',              url: 'about'}
- {name: 'Contacto',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:

- {icon: 'instagram', link:  'https://www.instagram.com/pedroolpzzz_/'}
- {icon: 'envelope', link:   'mailto:ped_lopcar@alu.iseacv.gva.es'}

# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Nuevo'
  previous_page: 'Antiguo'

sharing_button_prompt: 'Se libre de compartir!'

related_posts: 'Tal vez te interese...'
post_date_prefix: 'Escrito el'

